name: "Tests"
on: [push]
permissions:
  contents: "read"
jobs:
  composer:
    name: Composer config validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate --strict
  php:
    name: PHP syntax validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PHP syntax
        run: php -l src/ tests/
  phpunit:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1, 8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
          command: install --ignore-platform-req=ext-eusphpe
      - run: vendor/bin/phpunit
